spring:
  profiles:
    active:
    - dev-1
---
server:
  port: 3321
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.junjiang.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
spring:
  profiles: dev-1
  application:
    name: freedom-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.116.42.103:3306/freedom
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 2000
        
eureka:
  client:
    service-url:
      defaultZone: http://1.116.42.103:3311/,http://120.77.238.28:3312/
  instance:
    instance-id: freedom-user:3321
    prefer-ip-address: true
    
info:
  app:
    name: freedom
  company:
    name: junjiang.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$
    
management:
  endpoints:
    web:
      exposure:
        include:
        - info
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
---
server:
  port: 3322
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.junjiang.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
spring:
  profiles: dev-2
  application:
    name: freedom-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.116.42.103:3306/freedom
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 2000
      

eureka:
  client:
    service-url:
      defaultZone: http://1.116.42.103:3311/,http://120.77.238.28:3312/
  instance:
    instance-id: freedom-user:3322
    prefer-ip-address: true
    
info:
  app:
    name: freedom
  company:
    name: junjiang.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$
    
management:
  endpoints:
    web:
      exposure:
        include:
        - info
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
